[package]
name = "AirCtrlMqtt"
version = "1.0.1"
edition = "2024"

[dependencies]
aircontrol = "1.0.0"
chrono = "0.4.41"
hidapi = "2.6.3"
rumqttc = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
