services:
  airctrl-mqtt:
    image: cupcaker/air-ctrl-mqtt:latest
    container_name: airctrl-mqtt
    environment:
      - MQTT_HOST=your-mqtt-broker-host
      - MQTT_PORT=1883
      - MQTT_CLIENT_ID=airctrl_client
      - MQTT_TOPIC=airctrl/sensors
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
    devices:
      - /dev/aircontrol:/dev/aircontrol
    restart: unless-stopped
    stop_grace_period: 2s
